name: 'dbt_rghesquieres_first'
version: '1.0.0'
config-version: 2

# Profil de connexion à BigQuery (par défaut)
profile: 'default'

# Chemins des dossiers dbt
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Répertoires supprimés avec `dbt clean`
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuration des modèles
models:
  dbt_rghesquieres_first:        
    staging:
      +materialized: view       # tous les stg_ en vue
    intermediate:
      +materialized: view       # int_ en vue (par défaut, mais changeable)
    mart:
      +materialized: table      # tous les mart_ en table