name: 'dbt_rghesquieres'
version: '1.0.0'
config-version: 2

# Profil de connexion à BigQuery (par défaut)
profile: 'default'

# Chemins des dossiers dbt
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Répertoires supprimés avec `dbt clean`
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuration des modèles
      
models:
  rghesquieres:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    mart:
      +materialized: table
      finance:
        +schema: finance