version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

sources:
  - name: raw
    schema: gz_raw_data
    description: "Dataset brut BigQuery avec alias simplifié"
    tables:
      - name: raw_gz_sales
        description: "Alias: sales"
        alias: sales
      - name: raw_gz_product
        description: "Alias: product"
        alias: product
      - name: raw_gz_ship
        description: "Alias: ship"
        alias: ship