
sources:
  - name: raw
    schema: gz_raw_data
    description: "Dataset brut BigQuery avec alias simplifié"
    tables:
      - name: sales
        identifier: raw_gz_sales
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship